language: node_js

node_js:
  - "6.10.0"

script:
  # deploy service to lambda
  - cd service-secret-santa-generator
  - npm install
  - npm test
  - npm install -g serverless
  - sls deploy
  # deploy UI to s3 bucket
  - cd ../ui-secret-santa
  - nvm install 8.11.1
  - nvm use 8.11.1
  - nvm list
  - npm install -g serverless
  - npm install
  - npm run build
  - sls s3sync